### ISSUE TITLE
Buy a Character on a market 

### ISSUE THREAD

**Issue by Ceel123** [CryptoBlades/cb-gitbook-wiki#10]
Hi, 
I’m new at cryptoblades and today morning I buy a character on a market and then I buy a sword (or whatever you name that) so I connect matemask and I done everything I was told to do but then I don’t receive the character and I can’t receive the sword too but they take me 0.0022BNB of fees so what’s wrong? And I start now because I receive the information that when I start today as a new member I receive a skill extra and this didn’t happened so what can I do? 
thank you

**Comment by seiyria** [comment]
GitHub is not an avenue for support. Keep it in discord.
