### ISSUE TITLE
Transaction failed but stamina deducted

### ISSUE THREAD

**Issue by Euanbrielle** [CryptoBlades/cb-gitbook-wiki#11]
Hi Cryptoblades,

I want to report this issue I encounter were my 40 stamina still deducted even an error was occured(error screenshot attached). I hope you can help my concern.

Link below is transaction details.

https://bscscan.com/tx/0x3c40194dd4e59116715e83bf70949bf4775ed615aa90ca69ebc1a51ffa6bda61

Thank you.

Regards,
Edmhar Macasinag

**Comment by ralphSQ** [comment]
You're in the wrong repo. Check #faq and #help in the discord server https://discord.gg/c5afzyQ3Q9
