### ISSUE TITLE
SKILL DEDUCTED

### ISSUE THREAD

**Issue by Nhuj27** [CryptoBlades/cb-gitbook-wiki#14]
Sir what happened to my Skill? Yesterday Aug. 9 in the Philippines I tried to forge x10 but it will not success due to insuffieciend metamask funds. I also tried to buy weapon but also insufficiend fund issue. Then I accidentally click the withdraw button but i Cancelled it. Then I wake up this morning my Skill was gone. more or less 0.7 skills. What happened? Can you review my account? Hoping to get back my hard earned SKill. Thanks.

**Comment by seiyria** [comment]
do not open issues on these repositories.

**Comment by Nhuj27** [comment]
where can i open this case? thanks

**Comment by seiyria** [comment]
ask a mod.

**Comment by Nhuj27** [comment]
Thanks
